id: 467eec30f76c4dc09e650df2b749b285
initial_creation_type: ocr
source_metadata:
  volumes:
    6c656b2fa4f24aa392ac3d8e3aef3257:
      base_file: v115.txt
      image_group_id: I1PD95961
      title: ''
      total_pages: 1880
      volume_number: 116
